// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flchain/committee/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4ca79a0d884e8, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4ca79a0d884e8, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetSubmissionRequest struct {
	LnodeId string `protobuf:"bytes,1,opt,name=lnodeId,proto3" json:"lnodeId,omitempty"`
	Round   uint64 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *QueryGetSubmissionRequest) Reset()         { *m = QueryGetSubmissionRequest{} }
func (m *QueryGetSubmissionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSubmissionRequest) ProtoMessage()    {}
func (*QueryGetSubmissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4ca79a0d884e8, []int{2}
}
func (m *QueryGetSubmissionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSubmissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSubmissionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSubmissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSubmissionRequest.Merge(m, src)
}
func (m *QueryGetSubmissionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSubmissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSubmissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSubmissionRequest proto.InternalMessageInfo

func (m *QueryGetSubmissionRequest) GetLnodeId() string {
	if m != nil {
		return m.LnodeId
	}
	return ""
}

func (m *QueryGetSubmissionRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type QueryGetSubmissionResponse struct {
	Submission *Submission `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
}

func (m *QueryGetSubmissionResponse) Reset()         { *m = QueryGetSubmissionResponse{} }
func (m *QueryGetSubmissionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSubmissionResponse) ProtoMessage()    {}
func (*QueryGetSubmissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4ca79a0d884e8, []int{3}
}
func (m *QueryGetSubmissionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSubmissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSubmissionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSubmissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSubmissionResponse.Merge(m, src)
}
func (m *QueryGetSubmissionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSubmissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSubmissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSubmissionResponse proto.InternalMessageInfo

func (m *QueryGetSubmissionResponse) GetSubmission() *Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

type QueryGetScoreRequest struct {
	Round   uint64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	CnodeId string `protobuf:"bytes,2,opt,name=cnodeId,proto3" json:"cnodeId,omitempty"`
	LnodeId string `protobuf:"bytes,3,opt,name=lnodeId,proto3" json:"lnodeId,omitempty"`
}

func (m *QueryGetScoreRequest) Reset()         { *m = QueryGetScoreRequest{} }
func (m *QueryGetScoreRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetScoreRequest) ProtoMessage()    {}
func (*QueryGetScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4ca79a0d884e8, []int{4}
}
func (m *QueryGetScoreRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetScoreRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetScoreRequest.Merge(m, src)
}
func (m *QueryGetScoreRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetScoreRequest proto.InternalMessageInfo

func (m *QueryGetScoreRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *QueryGetScoreRequest) GetCnodeId() string {
	if m != nil {
		return m.CnodeId
	}
	return ""
}

func (m *QueryGetScoreRequest) GetLnodeId() string {
	if m != nil {
		return m.LnodeId
	}
	return ""
}

type QueryGetScoreResponse struct {
	ScoreJson string `protobuf:"bytes,1,opt,name=scoreJson,proto3" json:"scoreJson,omitempty"`
}

func (m *QueryGetScoreResponse) Reset()         { *m = QueryGetScoreResponse{} }
func (m *QueryGetScoreResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetScoreResponse) ProtoMessage()    {}
func (*QueryGetScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf4ca79a0d884e8, []int{5}
}
func (m *QueryGetScoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetScoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetScoreResponse.Merge(m, src)
}
func (m *QueryGetScoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetScoreResponse proto.InternalMessageInfo

func (m *QueryGetScoreResponse) GetScoreJson() string {
	if m != nil {
		return m.ScoreJson
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "flchain.committee.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "flchain.committee.QueryParamsResponse")
	proto.RegisterType((*QueryGetSubmissionRequest)(nil), "flchain.committee.QueryGetSubmissionRequest")
	proto.RegisterType((*QueryGetSubmissionResponse)(nil), "flchain.committee.QueryGetSubmissionResponse")
	proto.RegisterType((*QueryGetScoreRequest)(nil), "flchain.committee.QueryGetScoreRequest")
	proto.RegisterType((*QueryGetScoreResponse)(nil), "flchain.committee.QueryGetScoreResponse")
}

func init() { proto.RegisterFile("flchain/committee/query.proto", fileDescriptor_2cf4ca79a0d884e8) }

var fileDescriptor_2cf4ca79a0d884e8 = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb3, 0x29, 0x0d, 0x64, 0x10, 0x87, 0x2e, 0x41, 0x4a, 0x4c, 0x6b, 0x8a, 0x25, 0x20,
	0xaa, 0x20, 0xab, 0x36, 0xaa, 0x84, 0xf8, 0x23, 0xa1, 0x5e, 0x10, 0x70, 0x01, 0xf7, 0x06, 0x07,
	0xd8, 0x38, 0x8b, 0xb1, 0x14, 0xef, 0xba, 0xde, 0x0d, 0xa2, 0x44, 0xbd, 0xf0, 0x04, 0x48, 0x3c,
	0x00, 0x57, 0xb8, 0xf1, 0x18, 0x3d, 0x16, 0x71, 0xe1, 0x84, 0x50, 0x82, 0xc4, 0x6b, 0x20, 0xaf,
	0xd7, 0x8e, 0x43, 0x1c, 0xc2, 0x25, 0xda, 0xdd, 0xf9, 0xe6, 0x9b, 0xdf, 0xcc, 0xc4, 0xb0, 0xf1,
	0x72, 0xe0, 0xbd, 0xa2, 0x01, 0x27, 0x9e, 0x08, 0xc3, 0x40, 0x29, 0xc6, 0xc8, 0xc1, 0x90, 0xc5,
	0x87, 0x9d, 0x28, 0x16, 0x4a, 0xe0, 0x35, 0x13, 0xee, 0xe4, 0x61, 0x6b, 0x8d, 0x86, 0x01, 0x17,
	0x44, 0xff, 0xa6, 0x2a, 0xab, 0xe1, 0x0b, 0x5f, 0xe8, 0x23, 0x49, 0x4e, 0xe6, 0x75, 0xdd, 0x17,
	0xc2, 0x1f, 0x30, 0x42, 0xa3, 0x80, 0x50, 0xce, 0x85, 0xa2, 0x2a, 0x10, 0x5c, 0x9a, 0xe8, 0x96,
	0x27, 0x64, 0x28, 0x24, 0xe9, 0x51, 0x69, 0x4a, 0x92, 0xd7, 0xdb, 0x3d, 0xa6, 0xe8, 0x36, 0x89,
	0xa8, 0x1f, 0x70, 0x2d, 0x36, 0x5a, 0x7b, 0x1e, 0x32, 0xa2, 0x31, 0x0d, 0x33, 0x2f, 0x67, 0x3e,
	0x2e, 0x87, 0xbd, 0x30, 0x90, 0x32, 0xf7, 0x70, 0x1a, 0x80, 0x9f, 0x24, 0x55, 0x1e, 0xeb, 0x44,
	0x97, 0x1d, 0x0c, 0x99, 0x54, 0xce, 0x3e, 0x9c, 0x9f, 0x79, 0x95, 0x91, 0xe0, 0x92, 0xe1, 0x3b,
	0x50, 0x4b, 0x0b, 0x34, 0xd1, 0x26, 0x6a, 0x9f, 0xdd, 0x69, 0x75, 0xe6, 0xe6, 0xd0, 0x49, 0x53,
	0xf6, 0xea, 0xc7, 0x3f, 0x2e, 0x55, 0x3e, 0xfd, 0xfe, 0xb2, 0x85, 0x5c, 0x93, 0xe3, 0x3c, 0x82,
	0x96, 0x36, 0xbd, 0xcf, 0xd4, 0x7e, 0x8e, 0x61, 0x2a, 0xe2, 0x26, 0x9c, 0x1e, 0x70, 0xd1, 0x67,
	0x0f, 0xfa, 0xda, 0xbb, 0xee, 0x66, 0x57, 0xdc, 0x80, 0xd5, 0x58, 0x0c, 0x79, 0xbf, 0x59, 0xdd,
	0x44, 0xed, 0x53, 0x6e, 0x7a, 0x71, 0x9e, 0x81, 0x55, 0x66, 0x66, 0x40, 0xef, 0x02, 0x4c, 0x3b,
	0x35, 0xb0, 0x1b, 0x25, 0xb0, 0x85, 0xd4, 0x42, 0x82, 0xf3, 0x02, 0x1a, 0xb9, 0xb9, 0x27, 0x62,
	0x96, 0x41, 0xe6, 0x28, 0xa8, 0x80, 0x92, 0xa0, 0x7b, 0x06, 0xbd, 0x9a, 0xa2, 0x9b, 0x6b, 0xb1,
	0xa9, 0x95, 0x99, 0xa6, 0x9c, 0x5d, 0xb8, 0xf0, 0x57, 0x05, 0x43, 0xbe, 0x0e, 0x75, 0x99, 0x3c,
	0x3c, 0x94, 0x06, 0xbc, 0xee, 0x4e, 0x1f, 0x76, 0xbe, 0xae, 0xc0, 0xaa, 0xce, 0xc3, 0x6f, 0xa1,
	0x96, 0x4e, 0x1a, 0x5f, 0x29, 0xe9, 0x6b, 0x7e, 0xa5, 0xd6, 0xd5, 0x65, 0xb2, 0x14, 0xc0, 0xb9,
	0xfc, 0xee, 0xdb, 0xaf, 0x0f, 0xd5, 0x8b, 0xb8, 0x45, 0x16, 0xfd, 0xbb, 0xf0, 0x67, 0x04, 0xe7,
	0x66, 0xe6, 0x8e, 0xaf, 0x2f, 0x32, 0x2f, 0xdb, 0xb5, 0x75, 0xe3, 0x3f, 0xd5, 0x86, 0xe8, 0xb6,
	0x26, 0xda, 0xc5, 0xdd, 0x12, 0x22, 0x9f, 0xa9, 0xe7, 0xd3, 0xc5, 0x91, 0x91, 0x99, 0xef, 0x11,
	0x19, 0xe9, 0xdd, 0x1c, 0xe1, 0x8f, 0x08, 0xce, 0x64, 0x43, 0xc6, 0xd7, 0xfe, 0x55, 0xb8, 0xb0,
	0x68, 0xab, 0xbd, 0x5c, 0x68, 0xe0, 0xee, 0x69, 0xb8, 0x5b, 0xf8, 0xe6, 0x22, 0xb8, 0x44, 0x9d,
	0xd1, 0x90, 0x91, 0x97, 0xf3, 0x65, 0xa4, 0x7b, 0xdd, 0xe3, 0xb1, 0x8d, 0x4e, 0xc6, 0x36, 0xfa,
	0x39, 0xb6, 0xd1, 0xfb, 0x89, 0x5d, 0x39, 0x99, 0xd8, 0x95, 0xef, 0x13, 0xbb, 0xf2, 0xb4, 0x95,
	0x59, 0xbe, 0x29, 0x98, 0xaa, 0xc3, 0x88, 0xc9, 0x5e, 0x4d, 0x7f, 0xbd, 0xdd, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x60, 0x84, 0x16, 0xde, 0xa8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetSubmission items.
	GetSubmission(ctx context.Context, in *QueryGetSubmissionRequest, opts ...grpc.CallOption) (*QueryGetSubmissionResponse, error)
	// Queries a list of GetScore items.
	GetScore(ctx context.Context, in *QueryGetScoreRequest, opts ...grpc.CallOption) (*QueryGetScoreResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/flchain.committee.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSubmission(ctx context.Context, in *QueryGetSubmissionRequest, opts ...grpc.CallOption) (*QueryGetSubmissionResponse, error) {
	out := new(QueryGetSubmissionResponse)
	err := c.cc.Invoke(ctx, "/flchain.committee.Query/GetSubmission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetScore(ctx context.Context, in *QueryGetScoreRequest, opts ...grpc.CallOption) (*QueryGetScoreResponse, error) {
	out := new(QueryGetScoreResponse)
	err := c.cc.Invoke(ctx, "/flchain.committee.Query/GetScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetSubmission items.
	GetSubmission(context.Context, *QueryGetSubmissionRequest) (*QueryGetSubmissionResponse, error)
	// Queries a list of GetScore items.
	GetScore(context.Context, *QueryGetScoreRequest) (*QueryGetScoreResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetSubmission(ctx context.Context, req *QueryGetSubmissionRequest) (*QueryGetSubmissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmission not implemented")
}
func (*UnimplementedQueryServer) GetScore(ctx context.Context, req *QueryGetScoreRequest) (*QueryGetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScore not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flchain.committee.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flchain.committee.Query/GetSubmission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSubmission(ctx, req.(*QueryGetSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flchain.committee.Query/GetScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetScore(ctx, req.(*QueryGetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flchain.committee.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetSubmission",
			Handler:    _Query_GetSubmission_Handler,
		},
		{
			MethodName: "GetScore",
			Handler:    _Query_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flchain/committee/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetSubmissionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSubmissionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSubmissionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x10
	}
	if len(m.LnodeId) > 0 {
		i -= len(m.LnodeId)
		copy(dAtA[i:], m.LnodeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LnodeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSubmissionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSubmissionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSubmissionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Submission != nil {
		{
			size, err := m.Submission.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetScoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetScoreRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetScoreRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LnodeId) > 0 {
		i -= len(m.LnodeId)
		copy(dAtA[i:], m.LnodeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.LnodeId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CnodeId) > 0 {
		i -= len(m.CnodeId)
		copy(dAtA[i:], m.CnodeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CnodeId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Round != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetScoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetScoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetScoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ScoreJson) > 0 {
		i -= len(m.ScoreJson)
		copy(dAtA[i:], m.ScoreJson)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ScoreJson)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetSubmissionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LnodeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Round != 0 {
		n += 1 + sovQuery(uint64(m.Round))
	}
	return n
}

func (m *QueryGetSubmissionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Submission != nil {
		l = m.Submission.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetScoreRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Round != 0 {
		n += 1 + sovQuery(uint64(m.Round))
	}
	l = len(m.CnodeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.LnodeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetScoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ScoreJson)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSubmissionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSubmissionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSubmissionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LnodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LnodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSubmissionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSubmissionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSubmissionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Submission == nil {
				m.Submission = &Submission{}
			}
			if err := m.Submission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetScoreRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetScoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetScoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CnodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CnodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LnodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LnodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetScoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetScoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetScoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScoreJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScoreJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
