// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package committee

import (
	binary "encoding/binary"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	math "math"
	reflect "reflect"
	sort "sort"
	sync "sync"
)

var _ protoreflect.Map = (*_CommitAtt_2_map)(nil)

type _CommitAtt_2_map struct {
	m *map[string]float64
}

func (x *_CommitAtt_2_map) Len() int {
	if x.m == nil {
		return 0
	}
	return len(*x.m)
}

func (x *_CommitAtt_2_map) Range(f func(protoreflect.MapKey, protoreflect.Value) bool) {
	if x.m == nil {
		return
	}
	for k, v := range *x.m {
		mapKey := (protoreflect.MapKey)(protoreflect.ValueOfString(k))
		mapValue := protoreflect.ValueOfFloat64(v)
		if !f(mapKey, mapValue) {
			break
		}
	}
}

func (x *_CommitAtt_2_map) Has(key protoreflect.MapKey) bool {
	if x.m == nil {
		return false
	}
	keyUnwrapped := key.String()
	concreteValue := keyUnwrapped
	_, ok := (*x.m)[concreteValue]
	return ok
}

func (x *_CommitAtt_2_map) Clear(key protoreflect.MapKey) {
	if x.m == nil {
		return
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	delete(*x.m, concreteKey)
}

func (x *_CommitAtt_2_map) Get(key protoreflect.MapKey) protoreflect.Value {
	if x.m == nil {
		return protoreflect.Value{}
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	v, ok := (*x.m)[concreteKey]
	if !ok {
		return protoreflect.Value{}
	}
	return protoreflect.ValueOfFloat64(v)
}

func (x *_CommitAtt_2_map) Set(key protoreflect.MapKey, value protoreflect.Value) {
	if !key.IsValid() || !value.IsValid() {
		panic("invalid key or value provided")
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	valueUnwrapped := value.Float()
	concreteValue := valueUnwrapped
	(*x.m)[concreteKey] = concreteValue
}

func (x *_CommitAtt_2_map) Mutable(key protoreflect.MapKey) protoreflect.Value {
	panic("should not call Mutable on protoreflect.Map whose value is not of type protoreflect.Message")
}

func (x *_CommitAtt_2_map) NewValue() protoreflect.Value {
	v := float64(0)
	return protoreflect.ValueOfFloat64(v)
}

func (x *_CommitAtt_2_map) IsValid() bool {
	return x.m != nil
}

var _ protoreflect.Map = (*_CommitAtt_3_map)(nil)

type _CommitAtt_3_map struct {
	m *map[string]float64
}

func (x *_CommitAtt_3_map) Len() int {
	if x.m == nil {
		return 0
	}
	return len(*x.m)
}

func (x *_CommitAtt_3_map) Range(f func(protoreflect.MapKey, protoreflect.Value) bool) {
	if x.m == nil {
		return
	}
	for k, v := range *x.m {
		mapKey := (protoreflect.MapKey)(protoreflect.ValueOfString(k))
		mapValue := protoreflect.ValueOfFloat64(v)
		if !f(mapKey, mapValue) {
			break
		}
	}
}

func (x *_CommitAtt_3_map) Has(key protoreflect.MapKey) bool {
	if x.m == nil {
		return false
	}
	keyUnwrapped := key.String()
	concreteValue := keyUnwrapped
	_, ok := (*x.m)[concreteValue]
	return ok
}

func (x *_CommitAtt_3_map) Clear(key protoreflect.MapKey) {
	if x.m == nil {
		return
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	delete(*x.m, concreteKey)
}

func (x *_CommitAtt_3_map) Get(key protoreflect.MapKey) protoreflect.Value {
	if x.m == nil {
		return protoreflect.Value{}
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	v, ok := (*x.m)[concreteKey]
	if !ok {
		return protoreflect.Value{}
	}
	return protoreflect.ValueOfFloat64(v)
}

func (x *_CommitAtt_3_map) Set(key protoreflect.MapKey, value protoreflect.Value) {
	if !key.IsValid() || !value.IsValid() {
		panic("invalid key or value provided")
	}
	keyUnwrapped := key.String()
	concreteKey := keyUnwrapped
	valueUnwrapped := value.Float()
	concreteValue := valueUnwrapped
	(*x.m)[concreteKey] = concreteValue
}

func (x *_CommitAtt_3_map) Mutable(key protoreflect.MapKey) protoreflect.Value {
	panic("should not call Mutable on protoreflect.Map whose value is not of type protoreflect.Message")
}

func (x *_CommitAtt_3_map) NewValue() protoreflect.Value {
	v := float64(0)
	return protoreflect.ValueOfFloat64(v)
}

func (x *_CommitAtt_3_map) IsValid() bool {
	return x.m != nil
}

var _ protoreflect.List = (*_CommitAtt_4_list)(nil)

type _CommitAtt_4_list struct {
	list *[]string
}

func (x *_CommitAtt_4_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CommitAtt_4_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CommitAtt_4_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CommitAtt_4_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CommitAtt_4_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CommitAtt at list field Ranking as it is not of Message kind"))
}

func (x *_CommitAtt_4_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CommitAtt_4_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CommitAtt_4_list) IsValid() bool {
	return x.list != nil
}

var _ protoreflect.List = (*_CommitAtt_6_list)(nil)

type _CommitAtt_6_list struct {
	list *[]string
}

func (x *_CommitAtt_6_list) Len() int {
	if x.list == nil {
		return 0
	}
	return len(*x.list)
}

func (x *_CommitAtt_6_list) Get(i int) protoreflect.Value {
	return protoreflect.ValueOfString((*x.list)[i])
}

func (x *_CommitAtt_6_list) Set(i int, value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	(*x.list)[i] = concreteValue
}

func (x *_CommitAtt_6_list) Append(value protoreflect.Value) {
	valueUnwrapped := value.String()
	concreteValue := valueUnwrapped
	*x.list = append(*x.list, concreteValue)
}

func (x *_CommitAtt_6_list) AppendMutable() protoreflect.Value {
	panic(fmt.Errorf("AppendMutable can not be called on message CommitAtt at list field Committee as it is not of Message kind"))
}

func (x *_CommitAtt_6_list) Truncate(n int) {
	*x.list = (*x.list)[:n]
}

func (x *_CommitAtt_6_list) NewElement() protoreflect.Value {
	v := ""
	return protoreflect.ValueOfString(v)
}

func (x *_CommitAtt_6_list) IsValid() bool {
	return x.list != nil
}

var (
	md_CommitAtt           protoreflect.MessageDescriptor
	fd_CommitAtt_round     protoreflect.FieldDescriptor
	fd_CommitAtt_ewmaMap   protoreflect.FieldDescriptor
	fd_CommitAtt_swMap     protoreflect.FieldDescriptor
	fd_CommitAtt_ranking   protoreflect.FieldDescriptor
	fd_CommitAtt_clNode    protoreflect.FieldDescriptor
	fd_CommitAtt_committee protoreflect.FieldDescriptor
)

func init() {
	file_flchain_committee_commit_att_proto_init()
	md_CommitAtt = File_flchain_committee_commit_att_proto.Messages().ByName("CommitAtt")
	fd_CommitAtt_round = md_CommitAtt.Fields().ByName("round")
	fd_CommitAtt_ewmaMap = md_CommitAtt.Fields().ByName("ewmaMap")
	fd_CommitAtt_swMap = md_CommitAtt.Fields().ByName("swMap")
	fd_CommitAtt_ranking = md_CommitAtt.Fields().ByName("ranking")
	fd_CommitAtt_clNode = md_CommitAtt.Fields().ByName("clNode")
	fd_CommitAtt_committee = md_CommitAtt.Fields().ByName("committee")
}

var _ protoreflect.Message = (*fastReflection_CommitAtt)(nil)

type fastReflection_CommitAtt CommitAtt

func (x *CommitAtt) ProtoReflect() protoreflect.Message {
	return (*fastReflection_CommitAtt)(x)
}

func (x *CommitAtt) slowProtoReflect() protoreflect.Message {
	mi := &file_flchain_committee_commit_att_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_CommitAtt_messageType fastReflection_CommitAtt_messageType
var _ protoreflect.MessageType = fastReflection_CommitAtt_messageType{}

type fastReflection_CommitAtt_messageType struct{}

func (x fastReflection_CommitAtt_messageType) Zero() protoreflect.Message {
	return (*fastReflection_CommitAtt)(nil)
}
func (x fastReflection_CommitAtt_messageType) New() protoreflect.Message {
	return new(fastReflection_CommitAtt)
}
func (x fastReflection_CommitAtt_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_CommitAtt
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_CommitAtt) Descriptor() protoreflect.MessageDescriptor {
	return md_CommitAtt
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_CommitAtt) Type() protoreflect.MessageType {
	return _fastReflection_CommitAtt_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_CommitAtt) New() protoreflect.Message {
	return new(fastReflection_CommitAtt)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_CommitAtt) Interface() protoreflect.ProtoMessage {
	return (*CommitAtt)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_CommitAtt) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Round != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Round)
		if !f(fd_CommitAtt_round, value) {
			return
		}
	}
	if len(x.EwmaMap) != 0 {
		value := protoreflect.ValueOfMap(&_CommitAtt_2_map{m: &x.EwmaMap})
		if !f(fd_CommitAtt_ewmaMap, value) {
			return
		}
	}
	if len(x.SwMap) != 0 {
		value := protoreflect.ValueOfMap(&_CommitAtt_3_map{m: &x.SwMap})
		if !f(fd_CommitAtt_swMap, value) {
			return
		}
	}
	if len(x.Ranking) != 0 {
		value := protoreflect.ValueOfList(&_CommitAtt_4_list{list: &x.Ranking})
		if !f(fd_CommitAtt_ranking, value) {
			return
		}
	}
	if x.ClNode != "" {
		value := protoreflect.ValueOfString(x.ClNode)
		if !f(fd_CommitAtt_clNode, value) {
			return
		}
	}
	if len(x.Committee) != 0 {
		value := protoreflect.ValueOfList(&_CommitAtt_6_list{list: &x.Committee})
		if !f(fd_CommitAtt_committee, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_CommitAtt) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "flchain.committee.CommitAtt.round":
		return x.Round != uint64(0)
	case "flchain.committee.CommitAtt.ewmaMap":
		return len(x.EwmaMap) != 0
	case "flchain.committee.CommitAtt.swMap":
		return len(x.SwMap) != 0
	case "flchain.committee.CommitAtt.ranking":
		return len(x.Ranking) != 0
	case "flchain.committee.CommitAtt.clNode":
		return x.ClNode != ""
	case "flchain.committee.CommitAtt.committee":
		return len(x.Committee) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: flchain.committee.CommitAtt"))
		}
		panic(fmt.Errorf("message flchain.committee.CommitAtt does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CommitAtt) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "flchain.committee.CommitAtt.round":
		x.Round = uint64(0)
	case "flchain.committee.CommitAtt.ewmaMap":
		x.EwmaMap = nil
	case "flchain.committee.CommitAtt.swMap":
		x.SwMap = nil
	case "flchain.committee.CommitAtt.ranking":
		x.Ranking = nil
	case "flchain.committee.CommitAtt.clNode":
		x.ClNode = ""
	case "flchain.committee.CommitAtt.committee":
		x.Committee = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: flchain.committee.CommitAtt"))
		}
		panic(fmt.Errorf("message flchain.committee.CommitAtt does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_CommitAtt) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "flchain.committee.CommitAtt.round":
		value := x.Round
		return protoreflect.ValueOfUint64(value)
	case "flchain.committee.CommitAtt.ewmaMap":
		if len(x.EwmaMap) == 0 {
			return protoreflect.ValueOfMap(&_CommitAtt_2_map{})
		}
		mapValue := &_CommitAtt_2_map{m: &x.EwmaMap}
		return protoreflect.ValueOfMap(mapValue)
	case "flchain.committee.CommitAtt.swMap":
		if len(x.SwMap) == 0 {
			return protoreflect.ValueOfMap(&_CommitAtt_3_map{})
		}
		mapValue := &_CommitAtt_3_map{m: &x.SwMap}
		return protoreflect.ValueOfMap(mapValue)
	case "flchain.committee.CommitAtt.ranking":
		if len(x.Ranking) == 0 {
			return protoreflect.ValueOfList(&_CommitAtt_4_list{})
		}
		listValue := &_CommitAtt_4_list{list: &x.Ranking}
		return protoreflect.ValueOfList(listValue)
	case "flchain.committee.CommitAtt.clNode":
		value := x.ClNode
		return protoreflect.ValueOfString(value)
	case "flchain.committee.CommitAtt.committee":
		if len(x.Committee) == 0 {
			return protoreflect.ValueOfList(&_CommitAtt_6_list{})
		}
		listValue := &_CommitAtt_6_list{list: &x.Committee}
		return protoreflect.ValueOfList(listValue)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: flchain.committee.CommitAtt"))
		}
		panic(fmt.Errorf("message flchain.committee.CommitAtt does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CommitAtt) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "flchain.committee.CommitAtt.round":
		x.Round = value.Uint()
	case "flchain.committee.CommitAtt.ewmaMap":
		mv := value.Map()
		cmv := mv.(*_CommitAtt_2_map)
		x.EwmaMap = *cmv.m
	case "flchain.committee.CommitAtt.swMap":
		mv := value.Map()
		cmv := mv.(*_CommitAtt_3_map)
		x.SwMap = *cmv.m
	case "flchain.committee.CommitAtt.ranking":
		lv := value.List()
		clv := lv.(*_CommitAtt_4_list)
		x.Ranking = *clv.list
	case "flchain.committee.CommitAtt.clNode":
		x.ClNode = value.Interface().(string)
	case "flchain.committee.CommitAtt.committee":
		lv := value.List()
		clv := lv.(*_CommitAtt_6_list)
		x.Committee = *clv.list
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: flchain.committee.CommitAtt"))
		}
		panic(fmt.Errorf("message flchain.committee.CommitAtt does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CommitAtt) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "flchain.committee.CommitAtt.ewmaMap":
		if x.EwmaMap == nil {
			x.EwmaMap = make(map[string]float64)
		}
		value := &_CommitAtt_2_map{m: &x.EwmaMap}
		return protoreflect.ValueOfMap(value)
	case "flchain.committee.CommitAtt.swMap":
		if x.SwMap == nil {
			x.SwMap = make(map[string]float64)
		}
		value := &_CommitAtt_3_map{m: &x.SwMap}
		return protoreflect.ValueOfMap(value)
	case "flchain.committee.CommitAtt.ranking":
		if x.Ranking == nil {
			x.Ranking = []string{}
		}
		value := &_CommitAtt_4_list{list: &x.Ranking}
		return protoreflect.ValueOfList(value)
	case "flchain.committee.CommitAtt.committee":
		if x.Committee == nil {
			x.Committee = []string{}
		}
		value := &_CommitAtt_6_list{list: &x.Committee}
		return protoreflect.ValueOfList(value)
	case "flchain.committee.CommitAtt.round":
		panic(fmt.Errorf("field round of message flchain.committee.CommitAtt is not mutable"))
	case "flchain.committee.CommitAtt.clNode":
		panic(fmt.Errorf("field clNode of message flchain.committee.CommitAtt is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: flchain.committee.CommitAtt"))
		}
		panic(fmt.Errorf("message flchain.committee.CommitAtt does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_CommitAtt) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "flchain.committee.CommitAtt.round":
		return protoreflect.ValueOfUint64(uint64(0))
	case "flchain.committee.CommitAtt.ewmaMap":
		m := make(map[string]float64)
		return protoreflect.ValueOfMap(&_CommitAtt_2_map{m: &m})
	case "flchain.committee.CommitAtt.swMap":
		m := make(map[string]float64)
		return protoreflect.ValueOfMap(&_CommitAtt_3_map{m: &m})
	case "flchain.committee.CommitAtt.ranking":
		list := []string{}
		return protoreflect.ValueOfList(&_CommitAtt_4_list{list: &list})
	case "flchain.committee.CommitAtt.clNode":
		return protoreflect.ValueOfString("")
	case "flchain.committee.CommitAtt.committee":
		list := []string{}
		return protoreflect.ValueOfList(&_CommitAtt_6_list{list: &list})
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: flchain.committee.CommitAtt"))
		}
		panic(fmt.Errorf("message flchain.committee.CommitAtt does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_CommitAtt) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in flchain.committee.CommitAtt", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_CommitAtt) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CommitAtt) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_CommitAtt) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_CommitAtt) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*CommitAtt)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Round != 0 {
			n += 1 + runtime.Sov(uint64(x.Round))
		}
		if len(x.EwmaMap) > 0 {
			SiZeMaP := func(k string, v float64) {
				mapEntrySize := 1 + len(k) + runtime.Sov(uint64(len(k))) + 1 + 8
				n += mapEntrySize + 1 + runtime.Sov(uint64(mapEntrySize))
			}
			if options.Deterministic {
				sortme := make([]string, 0, len(x.EwmaMap))
				for k := range x.EwmaMap {
					sortme = append(sortme, k)
				}
				sort.Strings(sortme)
				for _, k := range sortme {
					v := x.EwmaMap[k]
					SiZeMaP(k, v)
				}
			} else {
				for k, v := range x.EwmaMap {
					SiZeMaP(k, v)
				}
			}
		}
		if len(x.SwMap) > 0 {
			SiZeMaP := func(k string, v float64) {
				mapEntrySize := 1 + len(k) + runtime.Sov(uint64(len(k))) + 1 + 8
				n += mapEntrySize + 1 + runtime.Sov(uint64(mapEntrySize))
			}
			if options.Deterministic {
				sortme := make([]string, 0, len(x.SwMap))
				for k := range x.SwMap {
					sortme = append(sortme, k)
				}
				sort.Strings(sortme)
				for _, k := range sortme {
					v := x.SwMap[k]
					SiZeMaP(k, v)
				}
			} else {
				for k, v := range x.SwMap {
					SiZeMaP(k, v)
				}
			}
		}
		if len(x.Ranking) > 0 {
			for _, s := range x.Ranking {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		l = len(x.ClNode)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if len(x.Committee) > 0 {
			for _, s := range x.Committee {
				l = len(s)
				n += 1 + l + runtime.Sov(uint64(l))
			}
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*CommitAtt)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Committee) > 0 {
			for iNdEx := len(x.Committee) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Committee[iNdEx])
				copy(dAtA[i:], x.Committee[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Committee[iNdEx])))
				i--
				dAtA[i] = 0x32
			}
		}
		if len(x.ClNode) > 0 {
			i -= len(x.ClNode)
			copy(dAtA[i:], x.ClNode)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ClNode)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Ranking) > 0 {
			for iNdEx := len(x.Ranking) - 1; iNdEx >= 0; iNdEx-- {
				i -= len(x.Ranking[iNdEx])
				copy(dAtA[i:], x.Ranking[iNdEx])
				i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Ranking[iNdEx])))
				i--
				dAtA[i] = 0x22
			}
		}
		if len(x.SwMap) > 0 {
			MaRsHaLmAp := func(k string, v float64) (protoiface.MarshalOutput, error) {
				baseI := i
				i -= 8
				binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(v))))
				i--
				dAtA[i] = 0x11
				i -= len(k)
				copy(dAtA[i:], k)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(k)))
				i--
				dAtA[i] = 0xa
				i = runtime.EncodeVarint(dAtA, i, uint64(baseI-i))
				i--
				dAtA[i] = 0x1a
				return protoiface.MarshalOutput{}, nil
			}
			if options.Deterministic {
				keysForSwMap := make([]string, 0, len(x.SwMap))
				for k := range x.SwMap {
					keysForSwMap = append(keysForSwMap, string(k))
				}
				sort.Slice(keysForSwMap, func(i, j int) bool {
					return keysForSwMap[i] < keysForSwMap[j]
				})
				for iNdEx := len(keysForSwMap) - 1; iNdEx >= 0; iNdEx-- {
					v := x.SwMap[string(keysForSwMap[iNdEx])]
					out, err := MaRsHaLmAp(keysForSwMap[iNdEx], v)
					if err != nil {
						return out, err
					}
				}
			} else {
				for k := range x.SwMap {
					v := x.SwMap[k]
					out, err := MaRsHaLmAp(k, v)
					if err != nil {
						return out, err
					}
				}
			}
		}
		if len(x.EwmaMap) > 0 {
			MaRsHaLmAp := func(k string, v float64) (protoiface.MarshalOutput, error) {
				baseI := i
				i -= 8
				binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(v))))
				i--
				dAtA[i] = 0x11
				i -= len(k)
				copy(dAtA[i:], k)
				i = runtime.EncodeVarint(dAtA, i, uint64(len(k)))
				i--
				dAtA[i] = 0xa
				i = runtime.EncodeVarint(dAtA, i, uint64(baseI-i))
				i--
				dAtA[i] = 0x12
				return protoiface.MarshalOutput{}, nil
			}
			if options.Deterministic {
				keysForEwmaMap := make([]string, 0, len(x.EwmaMap))
				for k := range x.EwmaMap {
					keysForEwmaMap = append(keysForEwmaMap, string(k))
				}
				sort.Slice(keysForEwmaMap, func(i, j int) bool {
					return keysForEwmaMap[i] < keysForEwmaMap[j]
				})
				for iNdEx := len(keysForEwmaMap) - 1; iNdEx >= 0; iNdEx-- {
					v := x.EwmaMap[string(keysForEwmaMap[iNdEx])]
					out, err := MaRsHaLmAp(keysForEwmaMap[iNdEx], v)
					if err != nil {
						return out, err
					}
				}
			} else {
				for k := range x.EwmaMap {
					v := x.EwmaMap[k]
					out, err := MaRsHaLmAp(k, v)
					if err != nil {
						return out, err
					}
				}
			}
		}
		if x.Round != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Round))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*CommitAtt)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CommitAtt: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CommitAtt: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
				}
				x.Round = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Round |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EwmaMap", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.EwmaMap == nil {
					x.EwmaMap = make(map[string]float64)
				}
				var mapkey string
				var mapvalue float64
				for iNdEx < postIndex {
					entryPreIndex := iNdEx
					var wire uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
						}
						if iNdEx >= l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						wire |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					fieldNum := int32(wire >> 3)
					if fieldNum == 1 {
						var stringLenmapkey uint64
						for shift := uint(0); ; shift += 7 {
							if shift >= 64 {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
							}
							if iNdEx >= l {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
							}
							b := dAtA[iNdEx]
							iNdEx++
							stringLenmapkey |= uint64(b&0x7F) << shift
							if b < 0x80 {
								break
							}
						}
						intStringLenmapkey := int(stringLenmapkey)
						if intStringLenmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						postStringIndexmapkey := iNdEx + intStringLenmapkey
						if postStringIndexmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if postStringIndexmapkey > l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
						iNdEx = postStringIndexmapkey
					} else if fieldNum == 2 {
						var mapvaluetemp uint64
						if (iNdEx + 8) > l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						mapvaluetemp = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
						iNdEx += 8
						mapvalue = math.Float64frombits(mapvaluetemp)
					} else {
						iNdEx = entryPreIndex
						skippy, err := runtime.Skip(dAtA[iNdEx:])
						if err != nil {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
						}
						if (skippy < 0) || (iNdEx+skippy) < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if (iNdEx + skippy) > postIndex {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						iNdEx += skippy
					}
				}
				x.EwmaMap[mapkey] = mapvalue
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwMap", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.SwMap == nil {
					x.SwMap = make(map[string]float64)
				}
				var mapkey string
				var mapvalue float64
				for iNdEx < postIndex {
					entryPreIndex := iNdEx
					var wire uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
						}
						if iNdEx >= l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						wire |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					fieldNum := int32(wire >> 3)
					if fieldNum == 1 {
						var stringLenmapkey uint64
						for shift := uint(0); ; shift += 7 {
							if shift >= 64 {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
							}
							if iNdEx >= l {
								return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
							}
							b := dAtA[iNdEx]
							iNdEx++
							stringLenmapkey |= uint64(b&0x7F) << shift
							if b < 0x80 {
								break
							}
						}
						intStringLenmapkey := int(stringLenmapkey)
						if intStringLenmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						postStringIndexmapkey := iNdEx + intStringLenmapkey
						if postStringIndexmapkey < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if postStringIndexmapkey > l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
						iNdEx = postStringIndexmapkey
					} else if fieldNum == 2 {
						var mapvaluetemp uint64
						if (iNdEx + 8) > l {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						mapvaluetemp = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
						iNdEx += 8
						mapvalue = math.Float64frombits(mapvaluetemp)
					} else {
						iNdEx = entryPreIndex
						skippy, err := runtime.Skip(dAtA[iNdEx:])
						if err != nil {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
						}
						if (skippy < 0) || (iNdEx+skippy) < 0 {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
						}
						if (iNdEx + skippy) > postIndex {
							return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
						}
						iNdEx += skippy
					}
				}
				x.SwMap[mapkey] = mapvalue
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Ranking", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Ranking = append(x.Ranking, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ClNode", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ClNode = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Committee", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Committee = append(x.Committee, string(dAtA[iNdEx:postIndex]))
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: flchain/committee/commit_att.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitAtt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round     uint64             `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	EwmaMap   map[string]float64 `protobuf:"bytes,2,rep,name=ewmaMap,proto3" json:"ewmaMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	SwMap     map[string]float64 `protobuf:"bytes,3,rep,name=swMap,proto3" json:"swMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	Ranking   []string           `protobuf:"bytes,4,rep,name=ranking,proto3" json:"ranking,omitempty"`
	ClNode    string             `protobuf:"bytes,5,opt,name=clNode,proto3" json:"clNode,omitempty"`
	Committee []string           `protobuf:"bytes,6,rep,name=committee,proto3" json:"committee,omitempty"`
}

func (x *CommitAtt) Reset() {
	*x = CommitAtt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flchain_committee_commit_att_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitAtt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAtt) ProtoMessage() {}

// Deprecated: Use CommitAtt.ProtoReflect.Descriptor instead.
func (*CommitAtt) Descriptor() ([]byte, []int) {
	return file_flchain_committee_commit_att_proto_rawDescGZIP(), []int{0}
}

func (x *CommitAtt) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CommitAtt) GetEwmaMap() map[string]float64 {
	if x != nil {
		return x.EwmaMap
	}
	return nil
}

func (x *CommitAtt) GetSwMap() map[string]float64 {
	if x != nil {
		return x.SwMap
	}
	return nil
}

func (x *CommitAtt) GetRanking() []string {
	if x != nil {
		return x.Ranking
	}
	return nil
}

func (x *CommitAtt) GetClNode() string {
	if x != nil {
		return x.ClNode
	}
	return ""
}

func (x *CommitAtt) GetCommittee() []string {
	if x != nil {
		return x.Committee
	}
	return nil
}

var File_flchain_committee_commit_att_proto protoreflect.FileDescriptor

var file_flchain_committee_commit_att_proto_rawDesc = []byte{
	0x0a, 0x22, 0x66, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x74, 0x65, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x22, 0xeb, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x41, 0x74, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x43, 0x0a, 0x07, 0x65,
	0x77, 0x6d, 0x61, 0x4d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x66,
	0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x74, 0x74, 0x2e, 0x45, 0x77, 0x6d, 0x61, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x77, 0x6d, 0x61, 0x4d, 0x61, 0x70,
	0x12, 0x3d, 0x0a, 0x05, 0x73, 0x77, 0x4d, 0x61, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x66, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x74, 0x65, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x74, 0x74, 0x2e, 0x53, 0x77,
	0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x77, 0x4d, 0x61, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x4e,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x1a,
	0x3a, 0x0a, 0x0c, 0x45, 0x77, 0x6d, 0x61, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x38, 0x0a, 0x0a, 0x53,
	0x77, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0xab, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6c,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x42,
	0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x74, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x1d, 0x66, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66,
	0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65,
	0xa2, 0x02, 0x03, 0x46, 0x43, 0x58, 0xaa, 0x02, 0x11, 0x46, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0xca, 0x02, 0x11, 0x46, 0x6c, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0xe2, 0x02,
	0x1d, 0x46, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x12, 0x46, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x74, 0x65, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flchain_committee_commit_att_proto_rawDescOnce sync.Once
	file_flchain_committee_commit_att_proto_rawDescData = file_flchain_committee_commit_att_proto_rawDesc
)

func file_flchain_committee_commit_att_proto_rawDescGZIP() []byte {
	file_flchain_committee_commit_att_proto_rawDescOnce.Do(func() {
		file_flchain_committee_commit_att_proto_rawDescData = protoimpl.X.CompressGZIP(file_flchain_committee_commit_att_proto_rawDescData)
	})
	return file_flchain_committee_commit_att_proto_rawDescData
}

var file_flchain_committee_commit_att_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flchain_committee_commit_att_proto_goTypes = []interface{}{
	(*CommitAtt)(nil), // 0: flchain.committee.CommitAtt
	nil,               // 1: flchain.committee.CommitAtt.EwmaMapEntry
	nil,               // 2: flchain.committee.CommitAtt.SwMapEntry
}
var file_flchain_committee_commit_att_proto_depIdxs = []int32{
	1, // 0: flchain.committee.CommitAtt.ewmaMap:type_name -> flchain.committee.CommitAtt.EwmaMapEntry
	2, // 1: flchain.committee.CommitAtt.swMap:type_name -> flchain.committee.CommitAtt.SwMapEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_flchain_committee_commit_att_proto_init() }
func file_flchain_committee_commit_att_proto_init() {
	if File_flchain_committee_commit_att_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flchain_committee_commit_att_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitAtt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flchain_committee_commit_att_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flchain_committee_commit_att_proto_goTypes,
		DependencyIndexes: file_flchain_committee_commit_att_proto_depIdxs,
		MessageInfos:      file_flchain_committee_commit_att_proto_msgTypes,
	}.Build()
	File_flchain_committee_commit_att_proto = out.File
	file_flchain_committee_commit_att_proto_rawDesc = nil
	file_flchain_committee_commit_att_proto_goTypes = nil
	file_flchain_committee_commit_att_proto_depIdxs = nil
}
