// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: flchain/committee/query.proto

package committee

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName        = "/flchain.committee.Query/Params"
	Query_GetSubmission_FullMethodName = "/flchain.committee.Query/GetSubmission"
	Query_GetScore_FullMethodName      = "/flchain.committee.Query/GetScore"
	Query_GetCommitAtt_FullMethodName  = "/flchain.committee.Query/GetCommitAtt"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetSubmission items.
	GetSubmission(ctx context.Context, in *QueryGetSubmissionRequest, opts ...grpc.CallOption) (*QueryGetSubmissionResponse, error)
	// Queries a list of GetScore items.
	GetScore(ctx context.Context, in *QueryGetScoreRequest, opts ...grpc.CallOption) (*QueryGetScoreResponse, error)
	// Queries a list of GetCommitAtt items.
	GetCommitAtt(ctx context.Context, in *QueryGetCommitAttRequest, opts ...grpc.CallOption) (*QueryGetCommitAttResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSubmission(ctx context.Context, in *QueryGetSubmissionRequest, opts ...grpc.CallOption) (*QueryGetSubmissionResponse, error) {
	out := new(QueryGetSubmissionResponse)
	err := c.cc.Invoke(ctx, Query_GetSubmission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetScore(ctx context.Context, in *QueryGetScoreRequest, opts ...grpc.CallOption) (*QueryGetScoreResponse, error) {
	out := new(QueryGetScoreResponse)
	err := c.cc.Invoke(ctx, Query_GetScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCommitAtt(ctx context.Context, in *QueryGetCommitAttRequest, opts ...grpc.CallOption) (*QueryGetCommitAttResponse, error) {
	out := new(QueryGetCommitAttResponse)
	err := c.cc.Invoke(ctx, Query_GetCommitAtt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetSubmission items.
	GetSubmission(context.Context, *QueryGetSubmissionRequest) (*QueryGetSubmissionResponse, error)
	// Queries a list of GetScore items.
	GetScore(context.Context, *QueryGetScoreRequest) (*QueryGetScoreResponse, error)
	// Queries a list of GetCommitAtt items.
	GetCommitAtt(context.Context, *QueryGetCommitAttRequest) (*QueryGetCommitAttResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetSubmission(context.Context, *QueryGetSubmissionRequest) (*QueryGetSubmissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmission not implemented")
}
func (UnimplementedQueryServer) GetScore(context.Context, *QueryGetScoreRequest) (*QueryGetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScore not implemented")
}
func (UnimplementedQueryServer) GetCommitAtt(context.Context, *QueryGetCommitAttRequest) (*QueryGetCommitAttResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommitAtt not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSubmission(ctx, req.(*QueryGetSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetScore(ctx, req.(*QueryGetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCommitAtt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCommitAttRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCommitAtt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetCommitAtt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCommitAtt(ctx, req.(*QueryGetCommitAttRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flchain.committee.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetSubmission",
			Handler:    _Query_GetSubmission_Handler,
		},
		{
			MethodName: "GetScore",
			Handler:    _Query_GetScore_Handler,
		},
		{
			MethodName: "GetCommitAtt",
			Handler:    _Query_GetCommitAtt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flchain/committee/query.proto",
}
